"""extend finance categories

Revision ID: 44bfa7fe62b7
Revises: e1fafe5e1ce2
Create Date: 2026-07-28 13:26:43.410244

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44bfa7fe62b7'
down_revision: str | Sequence[str] | None = 'e1fafe5e1ce2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    op.execute("ALTER TYPE financecategory ADD VALUE IF NOT EXISTS 'ALCOHOL'")
    op.execute("ALTER TYPE financecategory ADD VALUE IF NOT EXISTS 'TOBACCO'")
    op.execute("ALTER TYPE financecategory ADD VALUE IF NOT EXISTS 'MEDICINE'")
    op.execute("ALTER TYPE financecategory ADD VALUE IF NOT EXISTS 'TRANSPORT'")


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
