"""add oauth authorization storage

Revision ID: 7679958675e4
Revises: 71a6d7a9b8f8
Create Date: 2026-08-27 16:58:21.283481

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7679958675e4'
down_revision: str | Sequence[str] | None = '71a6d7a9b8f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_authorization_requests',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('client_state', sa.Text(), nullable=True),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('redirect_uri_provided_explicitly', sa.Boolean(), nullable=False),
    sa.Column('resource', sa.Text(), nullable=True),
    sa.Column('code_challenge', sa.Text(), nullable=False),
    sa.Column('telegram_nonce', sa.String(length=128), nullable=False),
    sa.Column('telegram_code_verifier', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_hash')
    )
    op.create_index(op.f('ix_oauth_authorization_requests_client_id'), 'oauth_authorization_requests', ['client_id'], unique=False)
    op.create_table('oauth_clients',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_metadata', sa.JSON(), nullable=False),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('oauth_authorization_codes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('redirect_uri_provided_explicitly', sa.Boolean(), nullable=False),
    sa.Column('resource', sa.Text(), nullable=True),
    sa.Column('code_challenge', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_index(op.f('ix_oauth_authorization_codes_client_id'), 'oauth_authorization_codes', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_authorization_codes_user_id'), 'oauth_authorization_codes', ['user_id'], unique=False)
    op.create_table('oauth_refresh_tokens',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_oauth_refresh_tokens_client_id'), 'oauth_refresh_tokens', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_refresh_tokens_user_id'), 'oauth_refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_refresh_tokens_user_id'), table_name='oauth_refresh_tokens')
    op.drop_index(op.f('ix_oauth_refresh_tokens_client_id'), table_name='oauth_refresh_tokens')
    op.drop_table('oauth_refresh_tokens')
    op.drop_index(op.f('ix_oauth_authorization_codes_user_id'), table_name='oauth_authorization_codes')
    op.drop_index(op.f('ix_oauth_authorization_codes_client_id'), table_name='oauth_authorization_codes')
    op.drop_table('oauth_authorization_codes')
    op.drop_table('oauth_clients')
    op.drop_index(op.f('ix_oauth_authorization_requests_client_id'), table_name='oauth_authorization_requests')
    op.drop_table('oauth_authorization_requests')
    # ### end Alembic commands ###
