"""add finance tables

Revision ID: e1fafe5e1ce2
Revises: 7c6318ed3b81
Create Date: 2026-07-27 19:59:20.798975

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fafe5e1ce2'
down_revision: str | Sequence[str] | None = '7c6318ed3b81'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operation_type', sa.Enum('EXPENSE', 'INCOME', name='operationtype'), nullable=False),
    sa.Column('place', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('finance_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('DAIRY', 'MEAT', 'VEGETABLES', 'FRUITS', 'DRINKS', 'HOUSEHOLD', 'OTHER', name='financecategory'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['finance_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finance_items')
    op.drop_table('finance_events')
    # ### end Alembic commands ###
