"""add finance gift part_time etc. categories

Revision ID: e8a80e534dbb
Revises: 44bfa7fe62b7
Create Date: 2026-07-29 16:48:26.419099

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a80e534dbb'
down_revision: str | Sequence[str] | None = '44bfa7fe62b7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    op.execute("ALTER TYPE financecategory ADD VALUE IF NOT EXISTS 'ONLINE_PAYMENTS'")
    op.execute("ALTER TYPE financecategory ADD VALUE IF NOT EXISTS 'HOME'")
    op.execute("ALTER TYPE financecategory ADD VALUE IF NOT EXISTS 'SALARY'")
    op.execute("ALTER TYPE financecategory ADD VALUE IF NOT EXISTS 'PART_TIME'")
    op.execute("ALTER TYPE financecategory ADD VALUE IF NOT EXISTS 'GIFT'")


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
