"""add finance categories grocery

Revision ID: eca1929127fd
Revises: e8a80e534dbb
Create Date: 2026-07-30 08:10:40.670901

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca1929127fd'
down_revision: str | Sequence[str] | None = 'e8a80e534dbb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    op.execute("ALTER TYPE financecategory ADD VALUE IF NOT EXISTS 'GROCERY'")


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
